### ISSUE TITLE
App not installed!

### ISSUE THREAD

**Issue by VTwo-Group** [Galarzaa90/android-things-rc522#1]
Hi
After execute: "there was a problem parsing the package!!!"
We compiled in android studio 2.3.3

Thanks.

**Comment by Galarzaa90** [comment]
Is that all that is shown? Can you provide more details please.

**Comment by VTwo-Group** [comment]
thanks.
problem fixed. but that needed android 7(minSdk 24, android things)!! 
how resolve this issue? (for android 5 or 6 with api level below 24)?

**Comment by VTwo-Group** [comment]
Do you have any other suggested code? Thanks

**Comment by Galarzaa90** [comment]
Nope, this was made specifically for Android Things, can't be run on any other devices.

You would need external hardware to be able to run this on a normal android device.

**Comment by VTwo-Group** [comment]
thanks.
