### ISSUE TITLE
Can't able to Write

### ISSUE THREAD

**Issue by sjnaveenkumar** [Galarzaa90/android-things-rc522#2]
i've tried writing a card with write function but it is always getting failed. Please look at my code

                byte blockAddress = 4;
                byte dataBlock[]    = {
                        0x01, 0x02, 0x03, 0x04, //  1,  2,   3,  4,
                        0x05, 0x06, 0x07, 0x08, //  5,  6,   7,  8,
                        0x08, 0x09, (byte) 0xff, 0x0b, //  9, 10, 255, 12,
                        0x0c, 0x0d, 0x0e, 0x0f  // 13, 14,  15, 16
                };
                if (mRrc522.write(blockAddress, dataBlock)) {
                    mTag.setVisibility(View.VISIBLE);
                    mTag.setText("SUCCESS");
                } else {
                    mTag.setVisibility(View.VISIBLE);
                    mTag.setText("FAIL");
                }

**Comment by Galarzaa90** [comment]
I found a problem in my code, I will run some tests and I will update as soon as possible, along with an example on how to do writes and reads.
