### ISSUE TITLE
UID is different

### ISSUE THREAD

**Issue by hibbert-de** [Galarzaa90/android-things-rc522#3]
Hi,
i'm using MIFARE Classic 1k cards. When I try to read the UID of the Tag, then I get a different ID than in other Projects with the same card.
I convert the Bytearray to a String using this function:
```
final protected static char[] hexArray = {'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'};
    private String bytesToHex(byte[] bytes) {
        char[] hexChars = new char[bytes.length * 2];
        int v;
        for ( int j = 0; j < bytes.length; j++ ) {
            v = bytes[j] & 0xFF;
            hexChars[j * 2] = hexArray[v >>> 4];
            hexChars[j * 2 + 1] = hexArray[v & 0x0F];
        }
        return new String(hexChars);
    }
```
The correct UID is: DD17380A but I get DD17380AF8.
The same with another Tag:
DB96007D -> DB96007D30

**Comment by Galarzaa90** [comment]
I don't have access to a MFRC522 at the moment, so I can't check this right now :/

**Comment by michaelroland** [comment]
See [Different NFC ID and RFID UID value](https://stackoverflow.com/q/50504463/2425802) on StackOverflow for an explanation of that difference.

**Comment by Mihkel23** [comment]
Hi, 
Thank you for great library! But i am getting also differen UID what i get ex. Python, Adriono and UID written back of the tag. Right now i am getting UID: 136-4-110-81-179 but it should be 046E51c2b33480. Can you suggest what i can change to get correct UID?
Thank you
